/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: modbus_service.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "modbus_service.pb-c.h"
void   modbus_service__version__init
                     (modbus_service__Version         *message)
{
  static modbus_service__Version init_value = modbus_service__VERSION__INIT;
  *message = init_value;
}
size_t modbus_service__version__get_packed_size
                     (const modbus_service__Version *message)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__version__pack
                     (const modbus_service__Version *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__version__pack_to_buffer
                     (const modbus_service__Version *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__Version *
       modbus_service__version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__Version *)
     protobuf_c_message_unpack (&modbus_service__version__descriptor,
                                allocator, len, data);
}
void   modbus_service__version__free_unpacked
                     (modbus_service__Version *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__event__init
                     (modbus_service__Event         *message)
{
  static modbus_service__Event init_value = modbus_service__EVENT__INIT;
  *message = init_value;
}
size_t modbus_service__event__get_packed_size
                     (const modbus_service__Event *message)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__event__pack
                     (const modbus_service__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__event__pack_to_buffer
                     (const modbus_service__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__Event *
       modbus_service__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__Event *)
     protobuf_c_message_unpack (&modbus_service__event__descriptor,
                                allocator, len, data);
}
void   modbus_service__event__free_unpacked
                     (modbus_service__Event *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__rectifier_output_present__init
                     (modbus_service__RectifierOutputPresent         *message)
{
  static modbus_service__RectifierOutputPresent init_value = modbus_service__RECTIFIER_OUTPUT_PRESENT__INIT;
  *message = init_value;
}
size_t modbus_service__rectifier_output_present__get_packed_size
                     (const modbus_service__RectifierOutputPresent *message)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output_present__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__rectifier_output_present__pack
                     (const modbus_service__RectifierOutputPresent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output_present__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__rectifier_output_present__pack_to_buffer
                     (const modbus_service__RectifierOutputPresent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output_present__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__RectifierOutputPresent *
       modbus_service__rectifier_output_present__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__RectifierOutputPresent *)
     protobuf_c_message_unpack (&modbus_service__rectifier_output_present__descriptor,
                                allocator, len, data);
}
void   modbus_service__rectifier_output_present__free_unpacked
                     (modbus_service__RectifierOutputPresent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output_present__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__rectifier_output__init
                     (modbus_service__RectifierOutput         *message)
{
  static modbus_service__RectifierOutput init_value = modbus_service__RECTIFIER_OUTPUT__INIT;
  *message = init_value;
}
size_t modbus_service__rectifier_output__get_packed_size
                     (const modbus_service__RectifierOutput *message)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__rectifier_output__pack
                     (const modbus_service__RectifierOutput *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__rectifier_output__pack_to_buffer
                     (const modbus_service__RectifierOutput *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__RectifierOutput *
       modbus_service__rectifier_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__RectifierOutput *)
     protobuf_c_message_unpack (&modbus_service__rectifier_output__descriptor,
                                allocator, len, data);
}
void   modbus_service__rectifier_output__free_unpacked
                     (modbus_service__RectifierOutput *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__rectifier_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__notify_rectifier_output__init
                     (modbus_service__NotifyRectifierOutput         *message)
{
  static modbus_service__NotifyRectifierOutput init_value = modbus_service__NOTIFY_RECTIFIER_OUTPUT__INIT;
  *message = init_value;
}
size_t modbus_service__notify_rectifier_output__get_packed_size
                     (const modbus_service__NotifyRectifierOutput *message)
{
  assert(message->base.descriptor == &modbus_service__notify_rectifier_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__notify_rectifier_output__pack
                     (const modbus_service__NotifyRectifierOutput *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__notify_rectifier_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__notify_rectifier_output__pack_to_buffer
                     (const modbus_service__NotifyRectifierOutput *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__notify_rectifier_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__NotifyRectifierOutput *
       modbus_service__notify_rectifier_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__NotifyRectifierOutput *)
     protobuf_c_message_unpack (&modbus_service__notify_rectifier_output__descriptor,
                                allocator, len, data);
}
void   modbus_service__notify_rectifier_output__free_unpacked
                     (modbus_service__NotifyRectifierOutput *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__notify_rectifier_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__set_comm_req__init
                     (modbus_service__SetCommReq         *message)
{
  static modbus_service__SetCommReq init_value = modbus_service__SET_COMM_REQ__INIT;
  *message = init_value;
}
size_t modbus_service__set_comm_req__get_packed_size
                     (const modbus_service__SetCommReq *message)
{
  assert(message->base.descriptor == &modbus_service__set_comm_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__set_comm_req__pack
                     (const modbus_service__SetCommReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__set_comm_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__set_comm_req__pack_to_buffer
                     (const modbus_service__SetCommReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__set_comm_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__SetCommReq *
       modbus_service__set_comm_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__SetCommReq *)
     protobuf_c_message_unpack (&modbus_service__set_comm_req__descriptor,
                                allocator, len, data);
}
void   modbus_service__set_comm_req__free_unpacked
                     (modbus_service__SetCommReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__set_comm_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__rectifier_error__init
                     (modbus_service__RectifierError         *message)
{
  static modbus_service__RectifierError init_value = modbus_service__RECTIFIER_ERROR__INIT;
  *message = init_value;
}
size_t modbus_service__rectifier_error__get_packed_size
                     (const modbus_service__RectifierError *message)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__rectifier_error__pack
                     (const modbus_service__RectifierError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__rectifier_error__pack_to_buffer
                     (const modbus_service__RectifierError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__RectifierError *
       modbus_service__rectifier_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__RectifierError *)
     protobuf_c_message_unpack (&modbus_service__rectifier_error__descriptor,
                                allocator, len, data);
}
void   modbus_service__rectifier_error__free_unpacked
                     (modbus_service__RectifierError *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__rectifier_error_detail__init
                     (modbus_service__RectifierErrorDetail         *message)
{
  static modbus_service__RectifierErrorDetail init_value = modbus_service__RECTIFIER_ERROR_DETAIL__INIT;
  *message = init_value;
}
size_t modbus_service__rectifier_error_detail__get_packed_size
                     (const modbus_service__RectifierErrorDetail *message)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error_detail__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__rectifier_error_detail__pack
                     (const modbus_service__RectifierErrorDetail *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error_detail__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__rectifier_error_detail__pack_to_buffer
                     (const modbus_service__RectifierErrorDetail *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error_detail__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__RectifierErrorDetail *
       modbus_service__rectifier_error_detail__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__RectifierErrorDetail *)
     protobuf_c_message_unpack (&modbus_service__rectifier_error_detail__descriptor,
                                allocator, len, data);
}
void   modbus_service__rectifier_error_detail__free_unpacked
                     (modbus_service__RectifierErrorDetail *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__rectifier_error_detail__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__rectifier_warning__init
                     (modbus_service__RectifierWarning         *message)
{
  static modbus_service__RectifierWarning init_value = modbus_service__RECTIFIER_WARNING__INIT;
  *message = init_value;
}
size_t modbus_service__rectifier_warning__get_packed_size
                     (const modbus_service__RectifierWarning *message)
{
  assert(message->base.descriptor == &modbus_service__rectifier_warning__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__rectifier_warning__pack
                     (const modbus_service__RectifierWarning *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__rectifier_warning__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__rectifier_warning__pack_to_buffer
                     (const modbus_service__RectifierWarning *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__rectifier_warning__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__RectifierWarning *
       modbus_service__rectifier_warning__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__RectifierWarning *)
     protobuf_c_message_unpack (&modbus_service__rectifier_warning__descriptor,
                                allocator, len, data);
}
void   modbus_service__rectifier_warning__free_unpacked
                     (modbus_service__RectifierWarning *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__rectifier_warning__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__rectifier_info__init
                     (modbus_service__RectifierInfo         *message)
{
  static modbus_service__RectifierInfo init_value = modbus_service__RECTIFIER_INFO__INIT;
  *message = init_value;
}
size_t modbus_service__rectifier_info__get_packed_size
                     (const modbus_service__RectifierInfo *message)
{
  assert(message->base.descriptor == &modbus_service__rectifier_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__rectifier_info__pack
                     (const modbus_service__RectifierInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__rectifier_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__rectifier_info__pack_to_buffer
                     (const modbus_service__RectifierInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__rectifier_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__RectifierInfo *
       modbus_service__rectifier_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__RectifierInfo *)
     protobuf_c_message_unpack (&modbus_service__rectifier_info__descriptor,
                                allocator, len, data);
}
void   modbus_service__rectifier_info__free_unpacked
                     (modbus_service__RectifierInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__rectifier_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__output_voltage__init
                     (modbus_service__OutputVoltage         *message)
{
  static modbus_service__OutputVoltage init_value = modbus_service__OUTPUT_VOLTAGE__INIT;
  *message = init_value;
}
size_t modbus_service__output_voltage__get_packed_size
                     (const modbus_service__OutputVoltage *message)
{
  assert(message->base.descriptor == &modbus_service__output_voltage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__output_voltage__pack
                     (const modbus_service__OutputVoltage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__output_voltage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__output_voltage__pack_to_buffer
                     (const modbus_service__OutputVoltage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__output_voltage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__OutputVoltage *
       modbus_service__output_voltage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__OutputVoltage *)
     protobuf_c_message_unpack (&modbus_service__output_voltage__descriptor,
                                allocator, len, data);
}
void   modbus_service__output_voltage__free_unpacked
                     (modbus_service__OutputVoltage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__output_voltage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__iso_status__init
                     (modbus_service__IsoStatus         *message)
{
  static modbus_service__IsoStatus init_value = modbus_service__ISO_STATUS__INIT;
  *message = init_value;
}
size_t modbus_service__iso_status__get_packed_size
                     (const modbus_service__IsoStatus *message)
{
  assert(message->base.descriptor == &modbus_service__iso_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__iso_status__pack
                     (const modbus_service__IsoStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__iso_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__iso_status__pack_to_buffer
                     (const modbus_service__IsoStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__iso_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__IsoStatus *
       modbus_service__iso_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__IsoStatus *)
     protobuf_c_message_unpack (&modbus_service__iso_status__descriptor,
                                allocator, len, data);
}
void   modbus_service__iso_status__free_unpacked
                     (modbus_service__IsoStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__iso_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__relay_status__init
                     (modbus_service__RelayStatus         *message)
{
  static modbus_service__RelayStatus init_value = modbus_service__RELAY_STATUS__INIT;
  *message = init_value;
}
size_t modbus_service__relay_status__get_packed_size
                     (const modbus_service__RelayStatus *message)
{
  assert(message->base.descriptor == &modbus_service__relay_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__relay_status__pack
                     (const modbus_service__RelayStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__relay_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__relay_status__pack_to_buffer
                     (const modbus_service__RelayStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__relay_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__RelayStatus *
       modbus_service__relay_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__RelayStatus *)
     protobuf_c_message_unpack (&modbus_service__relay_status__descriptor,
                                allocator, len, data);
}
void   modbus_service__relay_status__free_unpacked
                     (modbus_service__RelayStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__relay_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__bus_status__init
                     (modbus_service__BusStatus         *message)
{
  static modbus_service__BusStatus init_value = modbus_service__BUS_STATUS__INIT;
  *message = init_value;
}
size_t modbus_service__bus_status__get_packed_size
                     (const modbus_service__BusStatus *message)
{
  assert(message->base.descriptor == &modbus_service__bus_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__bus_status__pack
                     (const modbus_service__BusStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__bus_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__bus_status__pack_to_buffer
                     (const modbus_service__BusStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__bus_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__BusStatus *
       modbus_service__bus_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__BusStatus *)
     protobuf_c_message_unpack (&modbus_service__bus_status__descriptor,
                                allocator, len, data);
}
void   modbus_service__bus_status__free_unpacked
                     (modbus_service__BusStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__bus_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__hv_self_test_info__init
                     (modbus_service__HvSelfTestInfo         *message)
{
  static modbus_service__HvSelfTestInfo init_value = modbus_service__HV_SELF_TEST_INFO__INIT;
  *message = init_value;
}
size_t modbus_service__hv_self_test_info__get_packed_size
                     (const modbus_service__HvSelfTestInfo *message)
{
  assert(message->base.descriptor == &modbus_service__hv_self_test_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__hv_self_test_info__pack
                     (const modbus_service__HvSelfTestInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__hv_self_test_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__hv_self_test_info__pack_to_buffer
                     (const modbus_service__HvSelfTestInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__hv_self_test_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__HvSelfTestInfo *
       modbus_service__hv_self_test_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__HvSelfTestInfo *)
     protobuf_c_message_unpack (&modbus_service__hv_self_test_info__descriptor,
                                allocator, len, data);
}
void   modbus_service__hv_self_test_info__free_unpacked
                     (modbus_service__HvSelfTestInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__hv_self_test_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__node_comm_lost__init
                     (modbus_service__NodeCommLost         *message)
{
  static modbus_service__NodeCommLost init_value = modbus_service__NODE_COMM_LOST__INIT;
  *message = init_value;
}
size_t modbus_service__node_comm_lost__get_packed_size
                     (const modbus_service__NodeCommLost *message)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__node_comm_lost__pack
                     (const modbus_service__NodeCommLost *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__node_comm_lost__pack_to_buffer
                     (const modbus_service__NodeCommLost *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
modbus_service__NodeCommLost *
       modbus_service__node_comm_lost__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (modbus_service__NodeCommLost *)
     protobuf_c_message_unpack (&modbus_service__node_comm_lost__descriptor,
                                allocator, len, data);
}
void   modbus_service__node_comm_lost__free_unpacked
                     (modbus_service__NodeCommLost *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor modbus_service__version__field_descriptors[3] =
{
  {
    "major",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__Version, major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__Version, minor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subminor",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__Version, subminor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__version__field_indices_by_name[] = {
  0,   /* field[0] = major */
  1,   /* field[1] = minor */
  2,   /* field[2] = subminor */
};
static const ProtobufCIntRange modbus_service__version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor modbus_service__version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.Version",
  "Version",
  "modbus_service__Version",
  "modbus_service",
  sizeof(modbus_service__Version),
  3,
  modbus_service__version__field_descriptors,
  modbus_service__version__field_indices_by_name,
  1,  modbus_service__version__number_ranges,
  (ProtobufCMessageInit) modbus_service__version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__event__field_descriptors[1] =
{
  {
    "event",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__Event, event),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__event__field_indices_by_name[] = {
  0,   /* field[0] = event */
};
static const ProtobufCIntRange modbus_service__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.Event",
  "Event",
  "modbus_service__Event",
  "modbus_service",
  sizeof(modbus_service__Event),
  1,
  modbus_service__event__field_descriptors,
  modbus_service__event__field_indices_by_name,
  1,  modbus_service__event__number_ranges,
  (ProtobufCMessageInit) modbus_service__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__rectifier_output_present__field_descriptors[2] =
{
  {
    "voltage",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierOutputPresent, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierOutputPresent, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__rectifier_output_present__field_indices_by_name[] = {
  1,   /* field[1] = current */
  0,   /* field[0] = voltage */
};
static const ProtobufCIntRange modbus_service__rectifier_output_present__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor modbus_service__rectifier_output_present__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.RectifierOutputPresent",
  "RectifierOutputPresent",
  "modbus_service__RectifierOutputPresent",
  "modbus_service",
  sizeof(modbus_service__RectifierOutputPresent),
  2,
  modbus_service__rectifier_output_present__field_descriptors,
  modbus_service__rectifier_output_present__field_indices_by_name,
  1,  modbus_service__rectifier_output_present__number_ranges,
  (ProtobufCMessageInit) modbus_service__rectifier_output_present__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__rectifier_output__field_descriptors[3] =
{
  {
    "rec_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierOutput, rec_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierOutput, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierOutput, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__rectifier_output__field_indices_by_name[] = {
  2,   /* field[2] = current */
  0,   /* field[0] = rec_id */
  1,   /* field[1] = voltage */
};
static const ProtobufCIntRange modbus_service__rectifier_output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor modbus_service__rectifier_output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.RectifierOutput",
  "RectifierOutput",
  "modbus_service__RectifierOutput",
  "modbus_service",
  sizeof(modbus_service__RectifierOutput),
  3,
  modbus_service__rectifier_output__field_descriptors,
  modbus_service__rectifier_output__field_indices_by_name,
  1,  modbus_service__rectifier_output__number_ranges,
  (ProtobufCMessageInit) modbus_service__rectifier_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__notify_rectifier_output__field_descriptors[1] =
{
  {
    "rec_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__NotifyRectifierOutput, rec_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__notify_rectifier_output__field_indices_by_name[] = {
  0,   /* field[0] = rec_id */
};
static const ProtobufCIntRange modbus_service__notify_rectifier_output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__notify_rectifier_output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.NotifyRectifierOutput",
  "NotifyRectifierOutput",
  "modbus_service__NotifyRectifierOutput",
  "modbus_service",
  sizeof(modbus_service__NotifyRectifierOutput),
  1,
  modbus_service__notify_rectifier_output__field_descriptors,
  modbus_service__notify_rectifier_output__field_indices_by_name,
  1,  modbus_service__notify_rectifier_output__number_ranges,
  (ProtobufCMessageInit) modbus_service__notify_rectifier_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__set_comm_req__field_descriptors[2] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__SetCommReq, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_enable",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__SetCommReq, is_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__set_comm_req__field_indices_by_name[] = {
  1,   /* field[1] = is_enable */
  0,   /* field[0] = node */
};
static const ProtobufCIntRange modbus_service__set_comm_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor modbus_service__set_comm_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.SetCommReq",
  "SetCommReq",
  "modbus_service__SetCommReq",
  "modbus_service",
  sizeof(modbus_service__SetCommReq),
  2,
  modbus_service__set_comm_req__field_descriptors,
  modbus_service__set_comm_req__field_indices_by_name,
  1,  modbus_service__set_comm_req__number_ranges,
  (ProtobufCMessageInit) modbus_service__set_comm_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__rectifier_error__field_descriptors[1] =
{
  {
    "is_error",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierError, is_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__rectifier_error__field_indices_by_name[] = {
  0,   /* field[0] = is_error */
};
static const ProtobufCIntRange modbus_service__rectifier_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__rectifier_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.RectifierError",
  "RectifierError",
  "modbus_service__RectifierError",
  "modbus_service",
  sizeof(modbus_service__RectifierError),
  1,
  modbus_service__rectifier_error__field_descriptors,
  modbus_service__rectifier_error__field_indices_by_name,
  1,  modbus_service__rectifier_error__number_ranges,
  (ProtobufCMessageInit) modbus_service__rectifier_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__rectifier_error_detail__field_descriptors[16] =
{
  {
    "output_short",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, output_short),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_comm_interrupt",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, inner_comm_interrupt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pfc_side_abnormal",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, pfc_side_abnormal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discharge_abnormal",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, discharge_abnormal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mdl_fault",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, mdl_fault),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mdl_protect",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, mdl_protect),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "over_temp",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, over_temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_over_voltage",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, output_over_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_comm_interrupt",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, can_comm_interrupt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mdl_id_repetition",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, mdl_id_repetition),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_unsharing",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, load_unsharing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_phase_lost",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, input_phase_lost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_unbalance",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, input_unbalance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_under_voltage",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, input_under_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_over_voltage",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, input_over_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mdl_pfc_side_off",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierErrorDetail, mdl_pfc_side_off),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__rectifier_error_detail__field_indices_by_name[] = {
  8,   /* field[8] = can_comm_interrupt */
  3,   /* field[3] = discharge_abnormal */
  1,   /* field[1] = inner_comm_interrupt */
  14,   /* field[14] = input_over_voltage */
  11,   /* field[11] = input_phase_lost */
  12,   /* field[12] = input_unbalance */
  13,   /* field[13] = input_under_voltage */
  10,   /* field[10] = load_unsharing */
  4,   /* field[4] = mdl_fault */
  9,   /* field[9] = mdl_id_repetition */
  15,   /* field[15] = mdl_pfc_side_off */
  5,   /* field[5] = mdl_protect */
  7,   /* field[7] = output_over_voltage */
  0,   /* field[0] = output_short */
  6,   /* field[6] = over_temp */
  2,   /* field[2] = pfc_side_abnormal */
};
static const ProtobufCIntRange modbus_service__rectifier_error_detail__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor modbus_service__rectifier_error_detail__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.RectifierErrorDetail",
  "RectifierErrorDetail",
  "modbus_service__RectifierErrorDetail",
  "modbus_service",
  sizeof(modbus_service__RectifierErrorDetail),
  16,
  modbus_service__rectifier_error_detail__field_descriptors,
  modbus_service__rectifier_error_detail__field_indices_by_name,
  1,  modbus_service__rectifier_error_detail__number_ranges,
  (ProtobufCMessageInit) modbus_service__rectifier_error_detail__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__rectifier_warning__field_descriptors[2] =
{
  {
    "fan_fault",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierWarning, fan_fault),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_limit",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierWarning, power_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__rectifier_warning__field_indices_by_name[] = {
  0,   /* field[0] = fan_fault */
  1,   /* field[1] = power_limit */
};
static const ProtobufCIntRange modbus_service__rectifier_warning__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor modbus_service__rectifier_warning__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.RectifierWarning",
  "RectifierWarning",
  "modbus_service__RectifierWarning",
  "modbus_service",
  sizeof(modbus_service__RectifierWarning),
  2,
  modbus_service__rectifier_warning__field_descriptors,
  modbus_service__rectifier_warning__field_indices_by_name,
  1,  modbus_service__rectifier_warning__number_ranges,
  (ProtobufCMessageInit) modbus_service__rectifier_warning__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__rectifier_info__field_descriptors[2] =
{
  {
    "mdl_off_state",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierInfo, mdl_off_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "walk_in_enable",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RectifierInfo, walk_in_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__rectifier_info__field_indices_by_name[] = {
  0,   /* field[0] = mdl_off_state */
  1,   /* field[1] = walk_in_enable */
};
static const ProtobufCIntRange modbus_service__rectifier_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor modbus_service__rectifier_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.RectifierInfo",
  "RectifierInfo",
  "modbus_service__RectifierInfo",
  "modbus_service",
  sizeof(modbus_service__RectifierInfo),
  2,
  modbus_service__rectifier_info__field_descriptors,
  modbus_service__rectifier_info__field_indices_by_name,
  1,  modbus_service__rectifier_info__number_ranges,
  (ProtobufCMessageInit) modbus_service__rectifier_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__output_voltage__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__OutputVoltage, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__output_voltage__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange modbus_service__output_voltage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__output_voltage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.OutputVoltage",
  "OutputVoltage",
  "modbus_service__OutputVoltage",
  "modbus_service",
  sizeof(modbus_service__OutputVoltage),
  1,
  modbus_service__output_voltage__field_descriptors,
  modbus_service__output_voltage__field_indices_by_name,
  1,  modbus_service__output_voltage__number_ranges,
  (ProtobufCMessageInit) modbus_service__output_voltage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__iso_status__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__IsoStatus, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__iso_status__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange modbus_service__iso_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__iso_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.IsoStatus",
  "IsoStatus",
  "modbus_service__IsoStatus",
  "modbus_service",
  sizeof(modbus_service__IsoStatus),
  1,
  modbus_service__iso_status__field_descriptors,
  modbus_service__iso_status__field_indices_by_name,
  1,  modbus_service__iso_status__number_ranges,
  (ProtobufCMessageInit) modbus_service__iso_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__relay_status__field_descriptors[2] =
{
  {
    "main",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RelayStatus, main),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "precharge",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__RelayStatus, precharge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__relay_status__field_indices_by_name[] = {
  0,   /* field[0] = main */
  1,   /* field[1] = precharge */
};
static const ProtobufCIntRange modbus_service__relay_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor modbus_service__relay_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.RelayStatus",
  "RelayStatus",
  "modbus_service__RelayStatus",
  "modbus_service",
  sizeof(modbus_service__RelayStatus),
  2,
  modbus_service__relay_status__field_descriptors,
  modbus_service__relay_status__field_indices_by_name,
  1,  modbus_service__relay_status__number_ranges,
  (ProtobufCMessageInit) modbus_service__relay_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__bus_status__field_descriptors[1] =
{
  {
    "is_idle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(modbus_service__BusStatus, is_idle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__bus_status__field_indices_by_name[] = {
  0,   /* field[0] = is_idle */
};
static const ProtobufCIntRange modbus_service__bus_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__bus_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.BusStatus",
  "BusStatus",
  "modbus_service__BusStatus",
  "modbus_service",
  sizeof(modbus_service__BusStatus),
  1,
  modbus_service__bus_status__field_descriptors,
  modbus_service__bus_status__field_indices_by_name,
  1,  modbus_service__bus_status__number_ranges,
  (ProtobufCMessageInit) modbus_service__bus_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__hv_self_test_info__field_descriptors[1] =
{
  {
    "self_test_info",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__HvSelfTestInfo, self_test_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__hv_self_test_info__field_indices_by_name[] = {
  0,   /* field[0] = self_test_info */
};
static const ProtobufCIntRange modbus_service__hv_self_test_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__hv_self_test_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.HvSelfTestInfo",
  "HvSelfTestInfo",
  "modbus_service__HvSelfTestInfo",
  "modbus_service",
  sizeof(modbus_service__HvSelfTestInfo),
  1,
  modbus_service__hv_self_test_info__field_descriptors,
  modbus_service__hv_self_test_info__field_indices_by_name,
  1,  modbus_service__hv_self_test_info__number_ranges,
  (ProtobufCMessageInit) modbus_service__hv_self_test_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__node_comm_lost__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(modbus_service__NodeCommLost, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__node_comm_lost__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange modbus_service__node_comm_lost__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__node_comm_lost__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.NodeCommLost",
  "NodeCommLost",
  "modbus_service__NodeCommLost",
  "modbus_service",
  sizeof(modbus_service__NodeCommLost),
  1,
  modbus_service__node_comm_lost__field_descriptors,
  modbus_service__node_comm_lost__field_indices_by_name,
  1,  modbus_service__node_comm_lost__number_ranges,
  (ProtobufCMessageInit) modbus_service__node_comm_lost__init,
  NULL,NULL,NULL    /* reserved[123] */
};