/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: modbus_service.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "modbus_service.pb-c.h"
void   modbus_service__version__init
                     (ModbusService__Version         *message)
{
  static ModbusService__Version init_value = MODBUS_SERVICE__VERSION__INIT;
  *message = init_value;
}
size_t modbus_service__version__get_packed_size
                     (const ModbusService__Version *message)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__version__pack
                     (const ModbusService__Version *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__version__pack_to_buffer
                     (const ModbusService__Version *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__Version *
       modbus_service__version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__Version *)
     protobuf_c_message_unpack (&modbus_service__version__descriptor,
                                allocator, len, data);
}
void   modbus_service__version__free_unpacked
                     (ModbusService__Version *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__event__init
                     (ModbusService__Event         *message)
{
  static ModbusService__Event init_value = MODBUS_SERVICE__EVENT__INIT;
  *message = init_value;
}
size_t modbus_service__event__get_packed_size
                     (const ModbusService__Event *message)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__event__pack
                     (const ModbusService__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__event__pack_to_buffer
                     (const ModbusService__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__Event *
       modbus_service__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__Event *)
     protobuf_c_message_unpack (&modbus_service__event__descriptor,
                                allocator, len, data);
}
void   modbus_service__event__free_unpacked
                     (ModbusService__Event *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__emeter_output__init
                     (ModbusService__EmeterOutput         *message)
{
  static ModbusService__EmeterOutput init_value = MODBUS_SERVICE__EMETER_OUTPUT__INIT;
  *message = init_value;
}
size_t modbus_service__emeter_output__get_packed_size
                     (const ModbusService__EmeterOutput *message)
{
  assert(message->base.descriptor == &modbus_service__emeter_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__emeter_output__pack
                     (const ModbusService__EmeterOutput *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__emeter_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__emeter_output__pack_to_buffer
                     (const ModbusService__EmeterOutput *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__emeter_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__EmeterOutput *
       modbus_service__emeter_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__EmeterOutput *)
     protobuf_c_message_unpack (&modbus_service__emeter_output__descriptor,
                                allocator, len, data);
}
void   modbus_service__emeter_output__free_unpacked
                     (ModbusService__EmeterOutput *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__emeter_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__emeter_error__init
                     (ModbusService__EmeterError         *message)
{
  static ModbusService__EmeterError init_value = MODBUS_SERVICE__EMETER_ERROR__INIT;
  *message = init_value;
}
size_t modbus_service__emeter_error__get_packed_size
                     (const ModbusService__EmeterError *message)
{
  assert(message->base.descriptor == &modbus_service__emeter_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__emeter_error__pack
                     (const ModbusService__EmeterError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__emeter_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__emeter_error__pack_to_buffer
                     (const ModbusService__EmeterError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__emeter_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__EmeterError *
       modbus_service__emeter_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__EmeterError *)
     protobuf_c_message_unpack (&modbus_service__emeter_error__descriptor,
                                allocator, len, data);
}
void   modbus_service__emeter_error__free_unpacked
                     (ModbusService__EmeterError *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__emeter_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__isocha_error__init
                     (ModbusService__IsochaError         *message)
{
  static ModbusService__IsochaError init_value = MODBUS_SERVICE__ISOCHA_ERROR__INIT;
  *message = init_value;
}
size_t modbus_service__isocha_error__get_packed_size
                     (const ModbusService__IsochaError *message)
{
  assert(message->base.descriptor == &modbus_service__isocha_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__isocha_error__pack
                     (const ModbusService__IsochaError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__isocha_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__isocha_error__pack_to_buffer
                     (const ModbusService__IsochaError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__isocha_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__IsochaError *
       modbus_service__isocha_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__IsochaError *)
     protobuf_c_message_unpack (&modbus_service__isocha_error__descriptor,
                                allocator, len, data);
}
void   modbus_service__isocha_error__free_unpacked
                     (ModbusService__IsochaError *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__isocha_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__isocha_iso_status__init
                     (ModbusService__IsochaIsoStatus         *message)
{
  static ModbusService__IsochaIsoStatus init_value = MODBUS_SERVICE__ISOCHA_ISO_STATUS__INIT;
  *message = init_value;
}
size_t modbus_service__isocha_iso_status__get_packed_size
                     (const ModbusService__IsochaIsoStatus *message)
{
  assert(message->base.descriptor == &modbus_service__isocha_iso_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__isocha_iso_status__pack
                     (const ModbusService__IsochaIsoStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__isocha_iso_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__isocha_iso_status__pack_to_buffer
                     (const ModbusService__IsochaIsoStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__isocha_iso_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__IsochaIsoStatus *
       modbus_service__isocha_iso_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__IsochaIsoStatus *)
     protobuf_c_message_unpack (&modbus_service__isocha_iso_status__descriptor,
                                allocator, len, data);
}
void   modbus_service__isocha_iso_status__free_unpacked
                     (ModbusService__IsochaIsoStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__isocha_iso_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__isocha_measure_control__init
                     (ModbusService__IsochaMeasureControl         *message)
{
  static ModbusService__IsochaMeasureControl init_value = MODBUS_SERVICE__ISOCHA_MEASURE_CONTROL__INIT;
  *message = init_value;
}
size_t modbus_service__isocha_measure_control__get_packed_size
                     (const ModbusService__IsochaMeasureControl *message)
{
  assert(message->base.descriptor == &modbus_service__isocha_measure_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__isocha_measure_control__pack
                     (const ModbusService__IsochaMeasureControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__isocha_measure_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__isocha_measure_control__pack_to_buffer
                     (const ModbusService__IsochaMeasureControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__isocha_measure_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__IsochaMeasureControl *
       modbus_service__isocha_measure_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__IsochaMeasureControl *)
     protobuf_c_message_unpack (&modbus_service__isocha_measure_control__descriptor,
                                allocator, len, data);
}
void   modbus_service__isocha_measure_control__free_unpacked
                     (ModbusService__IsochaMeasureControl *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__isocha_measure_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modbus_service__node_comm_lost__init
                     (ModbusService__NodeCommLost         *message)
{
  static ModbusService__NodeCommLost init_value = MODBUS_SERVICE__NODE_COMM_LOST__INIT;
  *message = init_value;
}
size_t modbus_service__node_comm_lost__get_packed_size
                     (const ModbusService__NodeCommLost *message)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modbus_service__node_comm_lost__pack
                     (const ModbusService__NodeCommLost *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modbus_service__node_comm_lost__pack_to_buffer
                     (const ModbusService__NodeCommLost *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModbusService__NodeCommLost *
       modbus_service__node_comm_lost__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModbusService__NodeCommLost *)
     protobuf_c_message_unpack (&modbus_service__node_comm_lost__descriptor,
                                allocator, len, data);
}
void   modbus_service__node_comm_lost__free_unpacked
                     (ModbusService__NodeCommLost *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modbus_service__node_comm_lost__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor modbus_service__version__field_descriptors[3] =
{
  {
    "major",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__Version, major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__Version, minor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subminor",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__Version, subminor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__version__field_indices_by_name[] = {
  0,   /* field[0] = major */
  1,   /* field[1] = minor */
  2,   /* field[2] = subminor */
};
static const ProtobufCIntRange modbus_service__version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor modbus_service__version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.Version",
  "Version",
  "ModbusService__Version",
  "modbus_service",
  sizeof(ModbusService__Version),
  3,
  modbus_service__version__field_descriptors,
  modbus_service__version__field_indices_by_name,
  1,  modbus_service__version__number_ranges,
  (ProtobufCMessageInit) modbus_service__version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__event__field_descriptors[1] =
{
  {
    "event",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__Event, event),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__event__field_indices_by_name[] = {
  0,   /* field[0] = event */
};
static const ProtobufCIntRange modbus_service__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.Event",
  "Event",
  "ModbusService__Event",
  "modbus_service",
  sizeof(ModbusService__Event),
  1,
  modbus_service__event__field_descriptors,
  modbus_service__event__field_indices_by_name,
  1,  modbus_service__event__number_ranges,
  (ProtobufCMessageInit) modbus_service__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__emeter_output__field_descriptors[4] =
{
  {
    "m_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__EmeterOutput, m_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__EmeterOutput, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__EmeterOutput, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__EmeterOutput, power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__emeter_output__field_indices_by_name[] = {
  2,   /* field[2] = current */
  0,   /* field[0] = m_id */
  3,   /* field[3] = power */
  1,   /* field[1] = voltage */
};
static const ProtobufCIntRange modbus_service__emeter_output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor modbus_service__emeter_output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.EmeterOutput",
  "EmeterOutput",
  "ModbusService__EmeterOutput",
  "modbus_service",
  sizeof(ModbusService__EmeterOutput),
  4,
  modbus_service__emeter_output__field_descriptors,
  modbus_service__emeter_output__field_indices_by_name,
  1,  modbus_service__emeter_output__number_ranges,
  (ProtobufCMessageInit) modbus_service__emeter_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__emeter_error__field_descriptors[1] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__EmeterError, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__emeter_error__field_indices_by_name[] = {
  0,   /* field[0] = error_code */
};
static const ProtobufCIntRange modbus_service__emeter_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__emeter_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.EmeterError",
  "EmeterError",
  "ModbusService__EmeterError",
  "modbus_service",
  sizeof(ModbusService__EmeterError),
  1,
  modbus_service__emeter_error__field_descriptors,
  modbus_service__emeter_error__field_indices_by_name,
  1,  modbus_service__emeter_error__number_ranges,
  (ProtobufCMessageInit) modbus_service__emeter_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__isocha_error__field_descriptors[1] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__IsochaError, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__isocha_error__field_indices_by_name[] = {
  0,   /* field[0] = error_code */
};
static const ProtobufCIntRange modbus_service__isocha_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__isocha_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.IsochaError",
  "IsochaError",
  "ModbusService__IsochaError",
  "modbus_service",
  sizeof(ModbusService__IsochaError),
  1,
  modbus_service__isocha_error__field_descriptors,
  modbus_service__isocha_error__field_indices_by_name,
  1,  modbus_service__isocha_error__number_ranges,
  (ProtobufCMessageInit) modbus_service__isocha_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__isocha_iso_status__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__IsochaIsoStatus, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__isocha_iso_status__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange modbus_service__isocha_iso_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__isocha_iso_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.IsochaIsoStatus",
  "IsochaIsoStatus",
  "ModbusService__IsochaIsoStatus",
  "modbus_service",
  sizeof(ModbusService__IsochaIsoStatus),
  1,
  modbus_service__isocha_iso_status__field_descriptors,
  modbus_service__isocha_iso_status__field_indices_by_name,
  1,  modbus_service__isocha_iso_status__number_ranges,
  (ProtobufCMessageInit) modbus_service__isocha_iso_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__isocha_measure_control__field_descriptors[1] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ModbusService__IsochaMeasureControl, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__isocha_measure_control__field_indices_by_name[] = {
  0,   /* field[0] = start */
};
static const ProtobufCIntRange modbus_service__isocha_measure_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__isocha_measure_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.IsochaMeasureControl",
  "IsochaMeasureControl",
  "ModbusService__IsochaMeasureControl",
  "modbus_service",
  sizeof(ModbusService__IsochaMeasureControl),
  1,
  modbus_service__isocha_measure_control__field_descriptors,
  modbus_service__isocha_measure_control__field_indices_by_name,
  1,  modbus_service__isocha_measure_control__number_ranges,
  (ProtobufCMessageInit) modbus_service__isocha_measure_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modbus_service__node_comm_lost__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ModbusService__NodeCommLost, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modbus_service__node_comm_lost__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange modbus_service__node_comm_lost__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modbus_service__node_comm_lost__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "modbus_service.NodeCommLost",
  "NodeCommLost",
  "ModbusService__NodeCommLost",
  "modbus_service",
  sizeof(ModbusService__NodeCommLost),
  1,
  modbus_service__node_comm_lost__field_descriptors,
  modbus_service__node_comm_lost__field_indices_by_name,
  1,  modbus_service__node_comm_lost__number_ranges,
  (ProtobufCMessageInit) modbus_service__node_comm_lost__init,
  NULL,NULL,NULL    /* reserved[123] */
};
